<a href="https://colab.research.google.com/github/caiochacon/ufpb_intro_cd/blob/main/Exerc%C3%ADcio_Caio_Lucas_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas x=2 e y=2.

In [20]:
import numpy as np

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI
    dist = np.sqrt(np.sum((p1 - p2)**2))
    return dist

In [52]:
a = np.array([5, 2])
b = np.array([-2, -1])
distance(a, b)

7.615773105863909

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [127]:
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    array = np.array([np.nan for i in range(len(points))])
    for i in range(len(points)): 
      array[i] = np.sqrt( np.sum ((p1 - points[i]) ** 2))
    return array

In [128]:
p1 = np.array([0, 0])
points = np.array([[1,1], [2,2]])
n_distances(p1, points)

array([1.41421356, 2.82842712])

## Teste

In [129]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
1 items had no tests:
    __main__
2 items passed all tests:
   3 tests in __main__.distance
   3 tests in __main__.n_distances
6 tests in 3 items.
6 passed and 0 failed.
Test passed.


TestResults(failed=0, attempted=6)